#!/usr/bin/env node

/**
 * Precompile app.js / PoolDetail.js for the analytics app (backlog 052).
 *
 * These ship to the browser as plain <script> tags — no in-browser Babel.
 * Source uses React.createElement exclusively (no JSX, see CLAUDE.md), so no
 * JSX transform is needed. What IS needed: app.js and PoolDetail.js are two
 * separate classic <script> tags sharing one global lexical scope. Each
 * declares `var { useState, ... } = React` — already fixed by hand to avoid
 * a `const` redeclaration collision — but other top-level `let`/`const`
 * bindings inside each file's App()/PoolDetail() function bodies can still
 * throw "Cannot access before initialization" (TDZ) if referenced (even just
 * in a dependency array) before their own declaration line runs. Previously
 * @babel/standalone's default transform silently downleveled all let/const
 * to var, which has no TDZ. This script runs the same downlevel via
 * @babel/plugin-transform-block-scoping so compiled output preserves that
 * exact behavior — nothing else about the code changes.
 *
 * Source files (app.js, PoolDetail.js) stay the edit surface, unbuilt.
 * Run `npm run compile` after editing them and commit the *.compiled.js
 * output (same pattern as the sitemap/token-page generators).
 */

const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const FILES = ['app.js', 'PoolDetail.js'];

// Pure: source string in, compiled string out. No disk access — this is what
// the test-chain freshness check calls, so verifying doesn't mutate the tree.
function transform(file, source) {
  const { code } = babel.transformSync(source, {
    filename: file,
    babelrc: false,
    configFile: false,
    plugins: ['@babel/plugin-transform-block-scoping'],
    compact: false
  });
  return `// GENERATED by compile-app.js from ${file} — do not hand-edit. Run \`npm run compile\`.\n${code}\n`;
}

function compile(file) {
  const srcPath = path.join(__dirname, file);
  const outPath = path.join(__dirname, file.replace(/\.js$/, '.compiled.js'));
  const source = fs.readFileSync(srcPath, 'utf8');
  fs.writeFileSync(outPath, transform(file, source));
  return outPath;
}

if (require.main === module) {
  for (const file of FILES) {
    const outPath = compile(file);
    console.log(`compiled ${file} -> ${path.relative(__dirname, outPath)}`);
  }
}

module.exports = { compile, transform, FILES };
