/* Unit + integration tests for edge/api-core.js + edge/agent-log.mjs's /api
   dispatch (backlog 227, spec 227). Plain Node, plain lane (no browser-
   driving test framework anywhere in this file or in anything it requires/
   imports — see run-tests.js's transitive-require lane classifier), no
   network.

   Population comes from the REAL, committed data/pools-snapshot.json
   (7,339 pools at the time this was written) — never a hardcoded pool
   list, per spec 227's acceptance criteria. Two of those criteria deserve
   a note up front, because the population itself resolves an ambiguity in
   the original spec text (confirmed by the coordinator's correction during
   this build):

     - The ANOMALY positive control is NATURAL: the committed snapshot
       genuinely contains pools whose total APY exceeds APY_SANITY_LIMIT
       (17 of them, independently re-derived below, never assumed).
     - The SUB-FLOOR positive control CANNOT be natural: the snapshot is
       generated by generate-pools-snapshot.js, which already applies the
       $100K TVL floor UPSTREAM (its own `isRailedIn()`) before writing the
       file — the snapshot's own envelope even states this via its
       `minTvlUsd` field. So genuinely no pool in data/pools-snapshot.json
       has tvlUsd below DEFAULT_MIN_TVL (asserted below, loudly, not
       silently assumed) — the floor's positive control is therefore
       DERIVED by cloning one real pool from the population and perturbing
       only its tvlUsd below the floor, exactly as product-loop-kit/specs/
       227-notes.md documents as a deliberate, evidence-based deviation
       from the spec's literal "derive from the snapshot" (which implicitly
       assumed a natural instance would exist). If a FUTURE snapshot ever
       does contain a natural sub-floor pool, this file prefers it over the
       synthetic one and logs which it used — never silently ignoring real
       data in favor of a fixture.

   Run: node test_api_worker.js */

'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

let passed = 0;
let total = 0;
function ok(cond, msg) { total++; assert.ok(cond, msg); passed++; }
function eq(a, b, msg) { total++; assert.strictEqual(a, b, msg); passed++; }

const ROOT = __dirname;
const EDGE_DIR = path.join(ROOT, 'edge');
const apiCore = require(path.join(EDGE_DIR, 'api-core.js'));

// ===========================================================================
// A. Population — load the REAL snapshot, never a fixture.
// ===========================================================================
console.log('A. population — data/pools-snapshot.json');

const SNAPSHOT_PATH = path.join(ROOT, 'data', 'pools-snapshot.json');
const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf8'));
ok(snapshot && Array.isArray(snapshot.pools), 'sanity: data/pools-snapshot.json has a .pools array (root is the envelope object, not the array itself)');
const POPULATION = snapshot.pools;
ok(POPULATION.length > 1000, `sanity: expected a real, large population, got ${POPULATION.length}`);
console.log(`  loaded ${POPULATION.length} pools, snapshot.minTvlUsd=${snapshot.minTvlUsd}`);

// ===========================================================================
// B. Mirror / set-equality, BOTH DIRECTIONS: app.js's literal rail constants
//    vs. what /api reports (via trust-rails.js, never re-declared in
//    api-core.js — see api-core.js's own header + the grep proof below).
// ===========================================================================
console.log('\nB. rail-constant mirror — app.js literals <-> /api rails block');

const appJsSrc = fs.readFileSync(path.join(ROOT, 'app.js'), 'utf8');
const apySanityMatch = appJsSrc.match(/const\s+APY_SANITY_LIMIT\s*=\s*(\d+(?:\.\d+)?)\s*;/);
const minTvlMatch = appJsSrc.match(/const\s+DEFAULT_MIN_TVL\s*=\s*(\d+(?:\.\d+)?)\s*;/);
ok(apySanityMatch, 'sanity: app.js must declare "const APY_SANITY_LIMIT = <number>;" for this regex to find');
ok(minTvlMatch, 'sanity: app.js must declare "const DEFAULT_MIN_TVL = <number>;" for this regex to find');
const APP_JS_APY_SANITY_LIMIT = Number(apySanityMatch[1]);
const APP_JS_DEFAULT_MIN_TVL = Number(minTvlMatch[1]);
console.log(`  parsed from app.js: APY_SANITY_LIMIT=${APP_JS_APY_SANITY_LIMIT}, DEFAULT_MIN_TVL=${APP_JS_DEFAULT_MIN_TVL}`);

// api-core.js must not declare either rail literal itself — grep-provable,
// asserted here too (not just eyeballed) so a regression fails this file,
// not just a manual review.
const apiCoreSrc = fs.readFileSync(path.join(EDGE_DIR, 'api-core.js'), 'utf8');
const strayApySanityLiteral = /(?<!APY_SANITY_LIMIT[\s\S]{0,40})\b1000\b(?!\d)/.test(apiCoreSrc);
const strayMinTvlLiteral = /\b100000\b/.test(apiCoreSrc);
ok(!strayMinTvlLiteral, 'api-core.js must not contain the literal 100000 anywhere (it must read DEFAULT_MIN_TVL from trust-rails.js, never redeclare it)');
ok(!/\b1000\b/.test(apiCoreSrc.replace(/require\(['"]\.\.\/trust-rails\.js['"]\)/g, '')), 'api-core.js must not contain the literal 1000 anywhere (it must read APY_SANITY_LIMIT from trust-rails.js, never redeclare it)');
void strayApySanityLiteral; // (kept only to document the lookbehind attempt above; the simpler whole-file check above is the actual assertion)

const rails = apiCore.buildRailsBlock(APP_JS_DEFAULT_MIN_TVL);
// Direction 1: app.js -> api-core.
eq(rails.apySanityLimit, APP_JS_APY_SANITY_LIMIT, 'api-core.js rails.apySanityLimit must equal app.js\'s APY_SANITY_LIMIT literal');
eq(rails.minTvl, APP_JS_DEFAULT_MIN_TVL, 'api-core.js rails.minTvl (at the default floor) must equal app.js\'s DEFAULT_MIN_TVL literal');
// Direction 2: api-core -> app.js (the same equality, asserted the other
// way round — spec 227 explicitly asks for "both directions"; a strictEqual
// is symmetric, but the point is neither value is ever compared to itself).
eq(APP_JS_APY_SANITY_LIMIT, rails.apySanityLimit, 'app.js\'s APY_SANITY_LIMIT literal must equal api-core.js rails.apySanityLimit (reverse direction)');
eq(APP_JS_DEFAULT_MIN_TVL, rails.minTvl, 'app.js\'s DEFAULT_MIN_TVL literal must equal api-core.js rails.minTvl (reverse direction)');

// Also via the real routes (not just buildRailsBlock called directly).
const healthResult = apiCore.handleApiRequest({ pathname: '/api/health', searchParams: new URLSearchParams(), pools: POPULATION });
eq(healthResult.body.rails.apySanityLimit, APP_JS_APY_SANITY_LIMIT, '/api/health rails.apySanityLimit mirrors app.js');
eq(healthResult.body.rails.minTvl, APP_JS_DEFAULT_MIN_TVL, '/api/health rails.minTvl mirrors app.js');
ok(typeof healthResult.body.rails.apySanityLimitExplanation === 'string' && healthResult.body.rails.apySanityLimitExplanation.length > 20, 'apySanityLimitExplanation is real prose');
ok(typeof healthResult.body.rails.minTvlExplanation === 'string' && healthResult.body.rails.minTvlExplanation.length > 20, 'minTvlExplanation is real prose');

// ===========================================================================
// C. Full-population invariant (not samples) + positive controls.
// ===========================================================================
console.log('\nC. full-population invariant + positive controls');

// Independent re-derivation — NOT calling apiCore.totalApy/isAnomalous here,
// so this is not a tautological self-check. Same expression app.js itself
// uses at every APY_SANITY_LIMIT call site (app.js:1965/2066/2166/2524/
// 2930/3694, confirmed this session) — but computed fresh, against the
// app.js-parsed constants from section B, not api-core.js's copy of them.
function independentTotalApy(p) {
  return (Number(p && p.apyBase) || 0) + (Number(p && p.apyReward) || 0);
}

const expectedAnomalous = POPULATION.filter((p) => independentTotalApy(p) > APP_JS_APY_SANITY_LIMIT);
const expectedSubFloor = POPULATION.filter((p) => (Number(p && p.tvlUsd) || 0) < APP_JS_DEFAULT_MIN_TVL);

// Vacuity guard (per the coordinator's correction): loud, not silent.
if (expectedAnomalous.length === 0) {
  throw new Error('VACUITY GUARD TRIPPED: data/pools-snapshot.json contains ZERO pools above APY_SANITY_LIMIT — ' +
    'the anomaly positive control cannot be tested from real data. This must not pass silently; investigate the ' +
    'snapshot before trusting this test run.');
}
console.log(`  found ${expectedAnomalous.length} NATURAL anomalous pools in the snapshot (max total APY ` +
  `${Math.max(...expectedAnomalous.map(independentTotalApy)).toFixed(2)}%) — using these as the anomaly positive control.`);

if (expectedSubFloor.length > 0) {
  console.log(`  found ${expectedSubFloor.length} NATURAL sub-floor pools — using a real one as the floor positive control (unexpected but preferred over synthetic).`);
} else {
  ok(snapshot.minTvlUsd === APP_JS_DEFAULT_MIN_TVL, 'sanity: snapshot.minTvlUsd equals the app.js floor — this IS why no natural sub-floor pool exists (generate-pools-snapshot.js floors upstream)');
  console.log('  0 natural sub-floor pools (expected: generate-pools-snapshot.js already floors at $100K upstream — snapshot.minTvlUsd confirms it). Falling back to a population-derived synthetic pool below.');
}

const expectedRailedCount = POPULATION.length - expectedAnomalous.length - expectedSubFloor.length;
ok(expectedRailedCount > 0, 'sanity: expected a non-trivial railed population');

// C1. The core-level invariant, over ALL 7,339 pools (not a sample):
//     api-core.js's OWN predicates must agree with the independent
//     app.js-derived classification for every single pool.
let mismatchCount = 0;
for (const p of POPULATION) {
  const expectedAnom = independentTotalApy(p) > APP_JS_APY_SANITY_LIMIT;
  const expectedFloor = (Number(p.tvlUsd) || 0) >= APP_JS_DEFAULT_MIN_TVL;
  if (apiCore.isAnomalous(p) !== expectedAnom) mismatchCount++;
  if (apiCore.meetsFloor(p, APP_JS_DEFAULT_MIN_TVL) !== expectedFloor) mismatchCount++;
}
eq(mismatchCount, 0, `api-core.js's isAnomalous/meetsFloor must agree with the independent app.js-derived classification for ALL ${POPULATION.length} pools (found ${mismatchCount} mismatches)`);

// C2. The ROUTE-level invariant: /api/pools's reported `count` (computed
//     internally from the SAME whole-population filter) must equal the
//     independently-derived expected total.
const poolsDefault = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams(), pools: POPULATION });
eq(poolsDefault.status, 200, '/api/pools returns 200');
eq(poolsDefault.body.count, expectedRailedCount, '/api/pools count must equal the independently-derived whole-population railed count');
eq(poolsDefault.body.returned, Math.min(apiCore.DEFAULT_LIMIT, expectedRailedCount), '/api/pools returned == min(DEFAULT_LIMIT, count)');

// C3. Every pool actually returned in a maximal page (limit=MAX_LIMIT) must
//     individually pass BOTH rails, re-checked independently (not via
//     api-core.js's own functions — literal arithmetic against the
//     app.js-parsed constants).
const poolsMaxPage = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams('limit=' + apiCore.MAX_LIMIT), pools: POPULATION });
eq(poolsMaxPage.body.pools.length, Math.min(apiCore.MAX_LIMIT, expectedRailedCount), 'max-page /api/pools returns exactly min(MAX_LIMIT, count) pools');
for (const returnedPool of poolsMaxPage.body.pools) {
  ok(independentTotalApy(returnedPool) <= APP_JS_APY_SANITY_LIMIT, `returned pool ${returnedPool.pool} must not exceed APY_SANITY_LIMIT (got ${independentTotalApy(returnedPool)}%)`);
  ok((Number(returnedPool.tvlUsd) || 0) >= APP_JS_DEFAULT_MIN_TVL, `returned pool ${returnedPool.pool} must meet the TVL floor (got $${returnedPool.tvlUsd})`);
}

// C4. POSITIVE CONTROL — anomaly, full coverage of the natural population
//     (ALL 17, not a sample): each known-anomalous pool, queried through
//     the real route via its own exact project+chain (a narrow enough
//     filter that it WOULD appear near the top of a small result set if
//     exclusion weren't applied), must be ABSENT from the response.
for (const anomPool of expectedAnomalous) {
  const scoped = apiCore.handleApiRequest({
    pathname: '/api/pools',
    searchParams: new URLSearchParams('project=' + encodeURIComponent(anomPool.project) + '&chain=' + encodeURIComponent(anomPool.chain) + '&limit=' + apiCore.MAX_LIMIT),
    pools: POPULATION,
  });
  const ids = scoped.body.pools.map((p) => p.pool);
  ok(!ids.includes(anomPool.pool), `known-anomalous pool ${anomPool.pool} (${anomPool.project}/${anomPool.chain}, total APY ${independentTotalApy(anomPool).toFixed(2)}%) must be ABSENT from its own project+chain /api/pools query`);
}
console.log(`  verified all ${expectedAnomalous.length} natural anomalous pools are absent from their own scoped /api/pools query`);

// Same pools, looked up individually, must be flagged (not excluded).
for (const anomPool of expectedAnomalous) {
  const single = apiCore.handleApiRequest({ pathname: '/api/pools/' + anomPool.pool, searchParams: new URLSearchParams(), pools: POPULATION });
  eq(single.status, 200, `/api/pools/${anomPool.pool} still resolves (flagged, not hidden)`);
  eq(single.body.anomalous, true, `/api/pools/${anomPool.pool} must report anomalous:true`);
  ok(typeof single.body.reason === 'string' && single.body.reason.length > 10, `/api/pools/${anomPool.pool} must carry a non-trivial reason string`);
}

// C5. POSITIVE CONTROL — TVL floor. Prefer a natural sub-floor pool if one
//     ever exists; otherwise derive one by cloning a REAL population pool
//     and perturbing only tvlUsd (never a hand-written fixture object).
let floorControlPool;
let floorControlPopulation;
if (expectedSubFloor.length > 0) {
  floorControlPool = expectedSubFloor[0];
  floorControlPopulation = POPULATION;
} else {
  const template = POPULATION[0];
  ok(template && typeof template === 'object', 'sanity: POPULATION[0] exists to clone from');
  floorControlPool = Object.assign({}, template, {
    pool: '227-derived-sub-floor-control',
    project: '227-derived-sub-floor-project',
    chain: template.chain,
    symbol: template.symbol,
    tvlUsd: APP_JS_DEFAULT_MIN_TVL - 1, // one dollar under the floor, derived from the real constant, never hardcoded
    apyBase: 1, apyReward: 0, // deliberately far from the anomaly limit — this control is ONLY about the floor
  });
  ok(!POPULATION.some((p) => p.pool === floorControlPool.pool), 'sanity: synthetic id does not collide with a real pool id');
  floorControlPopulation = POPULATION.concat([floorControlPool]);
}
ok((Number(floorControlPool.tvlUsd) || 0) < APP_JS_DEFAULT_MIN_TVL, 'sanity: the floor control pool is genuinely below the floor');
ok(independentTotalApy(floorControlPool) <= APP_JS_APY_SANITY_LIMIT, 'sanity: the floor control pool is NOT also anomalous (isolates the floor rail specifically)');

const floorScoped = apiCore.handleApiRequest({
  pathname: '/api/pools',
  searchParams: new URLSearchParams('project=' + encodeURIComponent(floorControlPool.project) + '&limit=' + apiCore.MAX_LIMIT),
  pools: floorControlPopulation,
});
ok(!floorScoped.body.pools.map((p) => p.pool).includes(floorControlPool.pool), 'the floor-control pool must be ABSENT from its own scoped /api/pools query');

const floorSingle = apiCore.handleApiRequest({ pathname: '/api/pools/' + floorControlPool.pool, searchParams: new URLSearchParams(), pools: floorControlPopulation });
eq(floorSingle.status, 200, 'the floor-control pool still resolves by id (belowMinTvl-flagged, not hidden)');
eq(floorSingle.body.belowMinTvl, true, 'the floor-control pool must report belowMinTvl:true on /api/pools/:id');

// ===========================================================================
// D. minTvl clamp-up behavior.
// ===========================================================================
console.log('\nD. minTvl clamp-up behavior');

const belowFloorReq = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams('minTvl=1'), pools: POPULATION });
eq(belowFloorReq.body.railsApplied.minTvl, APP_JS_DEFAULT_MIN_TVL, 'a minTvl below the floor clamps UP to the default floor');
eq(belowFloorReq.body.railsApplied.minTvlClamped, true, 'a minTvl below the floor reports minTvlClamped:true');
eq(belowFloorReq.body.count, expectedRailedCount, 'a clamped-up minTvl=1 request returns the SAME count as the unfiltered default (proves the clamp, not just the label)');

const aboveFloorMinTvl = APP_JS_DEFAULT_MIN_TVL * 100;
const expectedAboveFloorCount = POPULATION.filter((p) => (Number(p.tvlUsd) || 0) >= aboveFloorMinTvl && independentTotalApy(p) <= APP_JS_APY_SANITY_LIMIT).length;
ok(expectedAboveFloorCount > 0 && expectedAboveFloorCount < expectedRailedCount, 'sanity: the above-floor minTvl used here must actually narrow the population (found ' + expectedAboveFloorCount + ')');
const aboveFloorReq = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams('minTvl=' + aboveFloorMinTvl), pools: POPULATION });
eq(aboveFloorReq.body.railsApplied.minTvl, aboveFloorMinTvl, 'a minTvl above the floor is honored exactly');
eq(aboveFloorReq.body.railsApplied.minTvlClamped, false, 'a minTvl above the floor is NOT reported as clamped');
eq(aboveFloorReq.body.count, expectedAboveFloorCount, 'an honored, above-floor minTvl narrows count to the independently-derived expectation');

// ===========================================================================
// E. limit default + cap.
// ===========================================================================
console.log('\nE. limit default + cap');

eq(apiCore.DEFAULT_LIMIT, 50, 'sanity: spec 227 pins the default limit at 50');
eq(apiCore.MAX_LIMIT, 200, 'sanity: spec 227 pins the max limit at 200');

const limitDefaultReq = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams(), pools: POPULATION });
eq(limitDefaultReq.body.railsApplied.limit, 50, 'no limit param -> default 50');
eq(limitDefaultReq.body.pools.length, 50, 'no limit param -> exactly 50 pools returned (population is large enough)');

const limitSmallReq = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams('limit=7'), pools: POPULATION });
eq(limitSmallReq.body.railsApplied.limit, 7, 'a small explicit limit is honored exactly');
eq(limitSmallReq.body.pools.length, 7, 'a small explicit limit returns exactly that many pools');

const limitHugeReq = apiCore.handleApiRequest({ pathname: '/api/pools', searchParams: new URLSearchParams('limit=999999'), pools: POPULATION });
eq(limitHugeReq.body.railsApplied.limit, 200, 'a limit above the max clamps DOWN to MAX_LIMIT');
eq(limitHugeReq.body.railsApplied.limitClamped, true, 'a limit above the max reports limitClamped:true');
eq(limitHugeReq.body.pools.length, 200, 'a clamped-down limit returns exactly MAX_LIMIT pools');

// ===========================================================================
// F. Unknown route -> 404 shape; rails on EVERY route including errors.
// ===========================================================================
console.log('\nF. unknown route 404 shape + rails on every route');

const unknown = apiCore.handleApiRequest({ pathname: '/api/definitely-not-a-route', searchParams: new URLSearchParams(), pools: POPULATION });
eq(unknown.status, 404, 'unknown /api/* -> 404');
ok(Array.isArray(unknown.body.endpoints) && unknown.body.endpoints.length >= 5, 'unknown-route 404 carries an endpoints list with all 5 documented routes');
ok(unknown.body.rails && typeof unknown.body.rails.apySanityLimit === 'number', 'unknown-route 404 carries a rails block');

const notFoundPool = apiCore.handleApiRequest({ pathname: '/api/pools/this-id-does-not-exist', searchParams: new URLSearchParams(), pools: POPULATION });
eq(notFoundPool.status, 404, '/api/pools/:id with an unknown id -> 404');
ok(notFoundPool.body.rails, '/api/pools/:id 404 carries a rails block');

function assertRailsBlock(body, label) {
  ok(body && body.rails, `${label}: response carries a rails object`);
  eq(typeof body.rails.apySanityLimit, 'number', `${label}: rails.apySanityLimit is a number`);
  eq(typeof body.rails.minTvl, 'number', `${label}: rails.minTvl is a number`);
  ok(typeof body.rails.apySanityLimitExplanation === 'string' && body.rails.apySanityLimitExplanation.length > 0, `${label}: rails.apySanityLimitExplanation is prose`);
  ok(typeof body.rails.minTvlExplanation === 'string' && body.rails.minTvlExplanation.length > 0, `${label}: rails.minTvlExplanation is prose`);
}

assertRailsBlock(apiCore.handleApiRequest({ pathname: '/api', searchParams: new URLSearchParams(), pools: POPULATION }).body, 'GET /api');
assertRailsBlock(healthResult.body, 'GET /api/health');
assertRailsBlock(poolsDefault.body, 'GET /api/pools');
assertRailsBlock(unknown.body, 'unknown /api/*');
assertRailsBlock(notFoundPool.body, 'GET /api/pools/:id (404)');
assertRailsBlock(apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams(), pools: POPULATION }).body, 'GET /api/forever-number (400, missing monthly)');
console.log('  rails block verified present + well-shaped on all 6 route/error combinations checked');

// ===========================================================================
// G. forever-number: mirrors planner.js:162 exactly (direct require, not a
//    copy), including the rate<=0 "not financeable" branch; blended-mode
//    derivation re-verified independently.
// ===========================================================================
console.log('\nG. forever-number semantics (mirrors planner.js:162)');

const planner = require(path.join(ROOT, 'planner.js'));
ok(typeof planner.foreverNumber === 'function', 'sanity: planner.js exports foreverNumber');

[[100, 5], [20, 2.5], [1000, 12], [50, 0.1]].forEach(([monthly, apy]) => {
  const expected = planner.foreverNumber(monthly, apy);
  const res = apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams(`monthly=${monthly}&apy=${apy}`), pools: POPULATION });
  eq(res.status, 200, `forever-number(${monthly}, ${apy}) -> 200`);
  eq(res.body.foreverNumber, expected, `forever-number(${monthly}, ${apy}) must equal planner.js's own foreverNumber() exactly (got ${res.body.foreverNumber}, expected ${expected})`);
  eq(res.body.financeable, Number.isFinite(expected), `financeable flag matches Number.isFinite(planner.js's result) for (${monthly}, ${apy})`);
});

// rate <= 0 -> not financeable (mirrors planner.js:164's exact branch).
[[100, 0], [100, -5]].forEach(([monthly, apy]) => {
  ok(!Number.isFinite(planner.foreverNumber(monthly, apy)), `sanity: planner.js's own foreverNumber(${monthly}, ${apy}) is Infinity (not financeable)`);
  const res = apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams(`monthly=${monthly}&apy=${apy}`), pools: POPULATION });
  eq(res.status, 200, `forever-number(${monthly}, ${apy}) with rate<=0 still returns 200 (it's an honest "no" answer, not a client error)`);
  eq(res.body.financeable, false, `forever-number(${monthly}, ${apy}) reports financeable:false`);
  eq(res.body.foreverNumber, null, `forever-number(${monthly}, ${apy}) reports foreverNumber:null, never Infinity/NaN (not JSON-safe)`);
  ok(typeof res.body.notFinanceableReason === 'string' && res.body.notFinanceableReason.length > 0, `forever-number(${monthly}, ${apy}) explains why in prose`);
  ok(/rate must be > 0/.test(res.body.notFinanceableReason), `forever-number(${monthly}, ${apy}) reason correctly attributes non-finiteness to the non-positive rate (got: ${res.body.notFinanceableReason})`);
});

// Overflow (verifier round 2, item 227, defect 1): a POSITIVE rate can still
// produce a non-finite foreverNumber via monthly*12/rate overflowing float
// range. The reason string must NOT blame "rate must be > 0" in that case —
// the rate is genuinely > 0, the capital figure is just unrepresentable.
// Two independently-derived overflow inputs, proving the branch split both
// ways (not just the new side): apyPct <= 0 still gets the old sentence
// (asserted above) and apyPct > 0 gets the new one (asserted here).
// Query strings are literal (not built via `${1e307}`, which JS renders as
// "1e+307" — the "+" is then decoded by URLSearchParams as a space and
// breaks the repro), matching the exact defect report's own URL shape.
[
  { qs: 'monthly=1e307&apy=1', monthly: 1e307, apy: 1 },
  { qs: 'monthly=1e300&apy=0.0000000001', monthly: 1e300, apy: 1e-10 },
].forEach(({ qs, monthly, apy }) => {
  ok(!Number.isFinite(planner.foreverNumber(monthly, apy)), `sanity: planner.js's own foreverNumber(${monthly}, ${apy}) is Infinity (overflow, not a rate<=0 case)`);
  const res = apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams(qs), pools: POPULATION });
  eq(res.status, 200, `forever-number(${qs}) overflow still returns 200`);
  eq(res.body.financeable, false, `forever-number(${qs}) overflow reports financeable:false`);
  eq(res.body.foreverNumber, null, `forever-number(${qs}) overflow reports foreverNumber:null`);
  ok(typeof res.body.notFinanceableReason === 'string' && res.body.notFinanceableReason.length > 0, `forever-number(${qs}) overflow explains why in prose`);
  ok(!/rate must be > 0/.test(res.body.notFinanceableReason), `forever-number(${qs}) overflow reason must NOT falsely claim the rate is non-positive (apyPct=${apy} is > 0) (got: ${res.body.notFinanceableReason})`);
  ok(!/cannot fund a recurring bill/.test(res.body.notFinanceableReason), `forever-number(${qs}) overflow reason must not reuse the rate<=0 sentence verbatim (got: ${res.body.notFinanceableReason})`);
});

// Blended mode (apy omitted): re-derive the TVL-weighted rate independently
// (not by calling apiCore.blendedRate — that would be tautological) and
// confirm the API's own blended apyPct matches it exactly.
const railedForBlend = POPULATION.filter((p) => (Number(p.tvlUsd) || 0) >= APP_JS_DEFAULT_MIN_TVL && independentTotalApy(p) <= APP_JS_APY_SANITY_LIMIT);
let tvlSum = 0, weightedApySum = 0;
for (const p of railedForBlend) {
  const tvl = Number(p.tvlUsd) || 0;
  tvlSum += tvl;
  weightedApySum += independentTotalApy(p) * tvl;
}
const expectedBlendedApy = tvlSum > 0 ? weightedApySum / tvlSum : 0;
const blendedRes = apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams('monthly=25'), pools: POPULATION });
eq(blendedRes.status, 200, 'forever-number with no apy param -> 200');
eq(blendedRes.body.apySource, 'blended', 'apySource reported as "blended" when apy param omitted');
ok(Math.abs(blendedRes.body.apyPct - expectedBlendedApy) < 1e-9, `blended apyPct must equal the independently-derived TVL-weighted rate (got ${blendedRes.body.apyPct}, expected ${expectedBlendedApy})`);
eq(blendedRes.body.foreverNumber, planner.foreverNumber(25, expectedBlendedApy), 'blended-mode foreverNumber must equal planner.js\'s own function applied to the derived rate');

// Bad requests.
eq(apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams(), pools: POPULATION }).status, 400, 'missing monthly -> 400');
eq(apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams('monthly=-5'), pools: POPULATION }).status, 400, 'non-positive monthly -> 400');
eq(apiCore.handleApiRequest({ pathname: '/api/forever-number', searchParams: new URLSearchParams('monthly=20&apy=notanumber'), pools: POPULATION }).status, 400, 'non-numeric apy -> 400');

// ===========================================================================
// I. Hostile/malformed `/api/pools/:id` segments (verifier round 1, item
//    227). The predicate under test is the WEAK one RAZOR.md calls for:
//    "no input to handleApiRequest may produce anything other than
//    { status, body } where body carries a rails block" — never "reject the
//    string 100%". A population, not a single repro string; and both the
//    plain api-core.js entry point AND the real edge/agent-log.mjs fetch()
//    are driven through it, since the original defect required BOTH layers
//    (an unguarded decodeURIComponent, and a try/catch that only wrapped
//    getPools()) to actually crash the Worker.
// ===========================================================================
console.log('\nI. hostile/malformed /api/pools/:id segments');

const HOSTILE_POOL_ID_SEGMENTS = [
  // The three exact strings the verifier reproduced the URIError with.
  { label: 'trailing-percent', segment: '100%' },
  { label: 'bare-percent', segment: '%' },
  { label: 'incomplete-multibyte-percent', segment: '%E0%A4%A' },
  // The rest of the population per the task's minimum list.
  { label: 'invalid-hex-percent', segment: '%zz' },
  { label: 'double-percent', segment: '%%' },
  { label: 'very-long-id', segment: 'x'.repeat(8192) },
  { label: 'embedded-newline', segment: 'abc\ndef' },
  { label: 'null-byte-encoded', segment: '%00' },
  { label: 'null-char-literal', segment: 'abc\u0000def' },
  { label: 'emoji', segment: '\u{1F600}' },
  { label: 'dot-dot', segment: '..' },
  { label: 'already-decoded-real-id', segment: POPULATION[0].pool },
];
ok(HOSTILE_POOL_ID_SEGMENTS.length >= 10, 'sanity: hostile pool-id population has at least the 10 minimum members the task asked for');

// I1. Core level (edge/api-core.js), pathname built directly — bypasses
// URL/new URL() entirely, so this also covers inputs a browser's URL parser
// would normalize away (e.g. "..") but a hand-built Request-like object
// passed straight to handleApiRequest would not.
for (const { label, segment } of HOSTILE_POOL_ID_SEGMENTS) {
  let threw = null;
  let result;
  try {
    result = apiCore.handleApiRequest({ pathname: '/api/pools/' + segment, searchParams: new URLSearchParams(), pools: POPULATION });
  } catch (err) {
    threw = err;
  }
  ok(!threw, `handleApiRequest(${label}) must never throw (threw: ${threw && threw.message})`);
  ok(result && typeof result.status === 'number', `handleApiRequest(${label}) returns a numeric status`);
  ok(result && result.body && typeof result.body === 'object', `handleApiRequest(${label}) returns a plain object body`);
  ok(result && result.body && result.body.rails && typeof result.body.rails.apySanityLimit === 'number', `handleApiRequest(${label}) body carries a rails block`);
}
console.log(`  I1: ${HOSTILE_POOL_ID_SEGMENTS.length}/${HOSTILE_POOL_ID_SEGMENTS.length} hostile segments handled without a throw, all carrying rails, via api-core.js directly`);

// The already-decoded real id must actually resolve (proves the guard's
// try/catch doesn't accidentally swallow the NORMAL, successful path too).
{
  const real = apiCore.handleApiRequest({ pathname: '/api/pools/' + POPULATION[0].pool, searchParams: new URLSearchParams(), pools: POPULATION });
  eq(real.status, 200, 'a normal, already-decoded real pool id still resolves 200 through the same code path');
  eq(real.body.pool, POPULATION[0].pool, 'the resolved pool is the one that was requested');
}

// Non-vacuity for the population itself: at least the three verifier-repro
// strings must be ones where decodeURIComponent actually throws — otherwise
// "the guard never fires" and I1 would pass vacuously.
const VERIFIER_REPRO_SEGMENTS = ['100%', '%', '%E0%A4%A'];
for (const s of VERIFIER_REPRO_SEGMENTS) {
  let decodeThrew = false;
  try { decodeURIComponent(s); } catch (_e) { decodeThrew = true; }
  ok(decodeThrew, `sanity: decodeURIComponent(${JSON.stringify(s)}) must itself throw — otherwise this isn't testing the guard at all`);
}

// ===========================================================================
// H. The real Worker (edge/agent-log.mjs): /api dispatch, CORS/OPTIONS,
//    503 on upstream failure, agent-read logging for /api paths, and the
//    non-/api byte-parity identity proof.
// ===========================================================================

function makeFakeDB() {
  const calls = [];
  const db = {
    prepare(sql) {
      return { bind(...args) { return { run() { calls.push({ sql, args }); return Promise.resolve({ success: true }); } }; } };
    },
  };
  return { db, calls };
}
function makeFakeCtx() {
  const waited = [];
  return { ctx: { waitUntil(p) { waited.push(p); } }, waited };
}
function makeRequest(url, opts) {
  opts = opts || {};
  return { url, method: opts.method || 'GET', headers: new Headers(opts.headers || {}), cf: opts.cf };
}

/** Distinguishes the two kinds of fetch() calls this Worker makes: a
 * string URL (getPools()'s call to yields.llama.fi) vs. a Request-like
 * object (the pass-through path's `fetch(request)`). This lets ONE stub
 * serve both the "pool data available" and "pass-through untouched"
 * scenarios in the same test run. */
function makeWorkerFetchStub({ poolsFail, poolsBody, passthroughResponse } = {}) {
  return async (input) => {
    if (typeof input === 'string') {
      if (poolsFail) return new Response('upstream broke', { status: 500 });
      return new Response(JSON.stringify({ status: 'success', data: poolsBody || [] }), { status: 200, headers: { 'content-type': 'application/json' } });
    }
    return passthroughResponse;
  };
}

async function runWorkerTests() {
  console.log('\nH. edge/agent-log.mjs — /api dispatch + non-/api byte-parity');

  const workerUrl = pathToFileURL(path.join(EDGE_DIR, 'agent-log.mjs')).href;
  const workerModule = await import(workerUrl);
  const worker = workerModule.default;
  ok(worker && typeof worker.fetch === 'function', 'sanity: the real edge/agent-log.mjs exports a default object with fetch()');
  ok(typeof workerModule.__resetPoolsMemoForTests === 'function', 'sanity: the test-only pools-memo reset hook is exported');

  const originalFetch = global.fetch;
  function setFetch(fn) { global.fetch = fn; }
  function restoreFetch() { global.fetch = originalFetch; }

  console.log('\nH1. GET /api/health -> 200 JSON, correct headers, agent-read logged as path_class "api"');
  {
    workerModule.__resetPoolsMemoForTests();
    setFetch(makeWorkerFetchStub({ poolsBody: POPULATION.slice(0, 20) }));
    const { db, calls } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const req = makeRequest('https://www.defi.garden/api/health', { headers: { 'user-agent': 'GPTBot/1.0', accept: 'application/json' } });
    const res = await worker.fetch(req, { DB: db }, ctx);
    await Promise.allSettled(waited);
    eq(res.status, 200, '/api/health -> 200');
    eq(res.headers.get('access-control-allow-origin'), '*', 'CORS header present on GET /api/health');
    eq(res.headers.get('cache-control'), 'public, max-age=300', 'Cache-Control present on GET /api/health');
    eq(res.headers.get('x-defi-garden-api-version'), apiCore.API_VERSION, 'X-Defi-Garden-Api-Version header matches api-core.js\'s API_VERSION');
    eq(res.headers.get('content-type'), 'application/json; charset=utf-8', 'JSON content-type on GET /api/health');
    const body = await res.json();
    eq(body.ok, true, '/api/health body.ok');
    ok(body.rails, '/api/health body carries rails');
    eq(calls.length, 1, 'exactly one agent_reads row written for a GET /api/health request');
    eq(calls[0].args[8], 'api', `agent_reads row's path_class must be "api" for /api/health (got ${calls[0].args[8]})`);
    eq(calls[0].args[6], 200, 'agent_reads row status matches the actual 200 response');
  }

  console.log('\nH2. OPTIONS /api/pools -> 204 with CORS headers, no pool fetch needed');
  {
    workerModule.__resetPoolsMemoForTests();
    let fetchCalled = false;
    setFetch(async () => { fetchCalled = true; return new Response('should not be reached', { status: 599 }); });
    const { db } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const req = makeRequest('https://www.defi.garden/api/pools', { method: 'OPTIONS' });
    const res = await worker.fetch(req, { DB: db }, ctx);
    await Promise.allSettled(waited);
    eq(res.status, 204, 'OPTIONS /api/pools -> 204');
    eq(res.headers.get('access-control-allow-origin'), '*', 'OPTIONS response carries CORS allow-origin');
    eq(res.headers.get('access-control-allow-methods'), 'GET, OPTIONS', 'OPTIONS response carries CORS allow-methods');
    eq(fetchCalled, false, 'OPTIONS preflight must never touch pool data (no fetch call)');
    // Verifier round 2, item 227, defect 2: API.md now scopes "every
    // response carries a rails object" to responses WITH a body. Pin that
    // doc claim to actual behavior — the 204 preflight has no body at all,
    // so there is nowhere for a rails object to live.
    eq(res.body, null, 'OPTIONS 204 preflight Response has a null body');
    const preflightText = await res.text();
    eq(preflightText, '', 'OPTIONS 204 preflight body reads as empty (no rails object, no JSON at all)');
  }

  console.log('\nH3. GET /api/pools -> 200 with real filtered/railed body, using the full population through the Worker');
  {
    workerModule.__resetPoolsMemoForTests();
    setFetch(makeWorkerFetchStub({ poolsBody: POPULATION }));
    const { db } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const req = makeRequest('https://www.defi.garden/api/pools?limit=5');
    const res = await worker.fetch(req, { DB: db }, ctx);
    await Promise.allSettled(waited);
    eq(res.status, 200, '/api/pools?limit=5 -> 200');
    const body = await res.json();
    eq(body.pools.length, 5, 'Worker-level /api/pools honors limit=5');
    eq(body.count, expectedRailedCount, 'Worker-level /api/pools count matches the same whole-population expectation as the direct api-core.js call');
  }

  console.log('\nH4. Upstream pool-data fetch failure -> 503 JSON carrying rails, never a throw, never pass-through');
  {
    workerModule.__resetPoolsMemoForTests();
    setFetch(makeWorkerFetchStub({ poolsFail: true }));
    const { db, calls } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const req = makeRequest('https://www.defi.garden/api/pools');
    let threw = null, res;
    try { res = await worker.fetch(req, { DB: db }, ctx); } catch (err) { threw = err; }
    await Promise.allSettled(waited);
    ok(!threw, `upstream failure must not throw (threw: ${threw && threw.message})`);
    eq(res.status, 503, 'upstream pool-data failure -> 503');
    const body = await res.json();
    eq(body.error, 'upstream_unavailable', '503 body carries error:"upstream_unavailable"');
    assertRailsBlock(body, '503 upstream_unavailable');
    eq(res.headers.get('cache-control'), 'no-store', 'verifier round 1: a 503 response must NOT be publicly cacheable (was public, max-age=300 before the fix)');
    eq(calls.length, 1, 'the 503 itself is still logged as an agent read');
    eq(calls[0].args[6], 503, 'agent_reads row records the real 503 status');
    eq(calls[0].args[8], 'api', '503 agent_reads row is still classified path_class "api"');
  }

  console.log('\nH5. non-/api request: PASS-THROUGH is untouched — SAME Response object, identity-checked');
  {
    workerModule.__resetPoolsMemoForTests();
    const sentinel = new Response('sentinel body', { status: 200, headers: { 'content-type': 'text/plain' } });
    setFetch(makeWorkerFetchStub({ passthroughResponse: sentinel }));
    const { db } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const req = makeRequest('https://www.defi.garden/style.css', { headers: { accept: 'text/css' } });
    const res = await worker.fetch(req, { DB: db }, ctx);
    await Promise.allSettled(waited);
    ok(res === sentinel, 'a non-/api request must return the EXACT SAME Response instance fetch(request) produced — untouched by the 227 diff');
  }

  console.log('\nH6. /api/health request: NOT the pass-through sentinel (identity must differ)');
  {
    workerModule.__resetPoolsMemoForTests();
    const sentinel = new Response('sentinel body', { status: 200, headers: { 'content-type': 'text/plain' } });
    // Same generic stub as H5 — the point of this case is that /api/health
    // is NEVER answered from the pass-through sentinel, regardless of what
    // getPools()'s fetch("https://yields.llama.fi/pools", ...) call receives.
    setFetch(makeWorkerFetchStub({ passthroughResponse: sentinel, poolsBody: [] }));
    const { db } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const req = makeRequest('https://www.defi.garden/api/health');
    const res = await worker.fetch(req, { DB: db }, ctx);
    await Promise.allSettled(waited);
    ok(res !== sentinel, '/api/health must NEVER return the pass-through sentinel Response — it is always answered from api-core.js');
  }

  console.log('\nH7. hostile/malformed /api/pools/:id segments driven through the REAL Worker fetch() — never a throw, always JSON with rails');
  {
    workerModule.__resetPoolsMemoForTests();
    setFetch(makeWorkerFetchStub({ poolsBody: POPULATION.slice(0, 50) }));
    const { db } = makeFakeDB();
    for (const { label, segment } of HOSTILE_POOL_ID_SEGMENTS) {
      const { ctx, waited } = makeFakeCtx();
      // Built directly as a URL string (not via encodeURIComponent) so the
      // literal, still-percent-escaped bytes reach `new URL(request.url)`
      // exactly as they would from a real hostile client — this is the
      // precise mechanism the verifier reproduced ("new URL(...).pathname
      // preserves the bare % ... these reach the handler").
      const req = makeRequest('https://www.defi.garden/api/pools/' + segment);
      let threw = null, res;
      try {
        res = await worker.fetch(req, { DB: db }, ctx);
      } catch (err) {
        threw = err;
      }
      await Promise.allSettled(waited);
      ok(!threw, `worker.fetch(/api/pools/${label}) must never throw (threw: ${threw && threw.message})`);
      ok(res && typeof res.status === 'number' && res.status >= 200 && res.status < 600, `worker.fetch(/api/pools/${label}) returns a real HTTP response`);
      let body = null, parseThrew = null;
      try { body = await res.json(); } catch (err) { parseThrew = err; }
      ok(!parseThrew, `worker.fetch(/api/pools/${label}) response body must be valid JSON (parse error: ${parseThrew && parseThrew.message})`);
      ok(body && body.rails && typeof body.rails.apySanityLimit === 'number', `worker.fetch(/api/pools/${label}) response body carries a rails block`);
    }
    console.log(`  H7: ${HOSTILE_POOL_ID_SEGMENTS.length}/${HOSTILE_POOL_ID_SEGMENTS.length} hostile segments answered with real JSON+rails through the real Worker, no throw`);
  }

  console.log('\nH8. defense in depth: a throwing apiCore.handleApiRequest must not escape worker.fetch() — 500 JSON with rails, non-cacheable');
  {
    workerModule.__resetPoolsMemoForTests();
    setFetch(makeWorkerFetchStub({ poolsBody: POPULATION.slice(0, 5) }));
    const { db, calls } = makeFakeDB();
    const { ctx, waited } = makeFakeCtx();
    const originalHandleApiRequest = apiCore.handleApiRequest;
    apiCore.handleApiRequest = function () {
      throw new Error('synthetic handler failure — verifier round 1 defense-in-depth test');
    };
    let threw = null, res;
    try {
      const req = makeRequest('https://www.defi.garden/api/pools');
      res = await worker.fetch(req, { DB: db }, ctx);
    } catch (err) {
      threw = err;
    } finally {
      apiCore.handleApiRequest = originalHandleApiRequest;
    }
    await Promise.allSettled(waited);
    ok(!threw, `a throwing handleApiRequest must not escape worker.fetch() (threw: ${threw && threw.message})`);
    eq(res.status, 500, 'a thrown handler error surfaces as a JSON 500, not an unhandled exception (previously: a Cloudflare 1101 error page)');
    eq(res.headers.get('cache-control'), 'no-store', 'a 500 internal_error response must not be publicly cacheable');
    const body = await res.json();
    eq(body.error, 'internal_error', '500 body carries error:"internal_error"');
    assertRailsBlock(body, '500 internal_error');
    eq(calls.length, 1, 'the 500 itself is still logged as an agent read, same discipline as the 503 path');
    eq(calls[0].args[6], 500, 'agent_reads row records the real 500 status');
    // Restored correctly: the NEXT normal request must succeed again.
    const { ctx: ctx2, waited: waited2 } = makeFakeCtx();
    const req2 = makeRequest('https://www.defi.garden/api/pools');
    const res2 = await worker.fetch(req2, { DB: db }, ctx2);
    await Promise.allSettled(waited2);
    eq(res2.status, 200, 'after restoring the original handleApiRequest, the next request succeeds normally again');
  }

  restoreFetch();
}

runWorkerTests()
  .then(() => {
    // `passed` and `total` are incremented together by ok()/eq() (total
    // first, then passed only once the assertion itself didn't throw), so
    // on a clean run they are equal by construction — this line prints the
    // real total attempted, not a value structurally forced to mirror
    // `passed` (verifier round 1, item 227: the old `${passed}/${passed}`
    // could never show a shortfall even if one existed).
    console.log(`\ntest_api_worker.js: ${passed}/${total} assertions passed`);
  })
  .catch((err) => {
    console.error(`test_api_worker.js: FAILED after ${passed}/${total} assertions passed`);
    console.error(err);
    process.exitCode = 1;
  });
