/* Acceptance tests for backlog 213 — Markdown twins of the pool-detail
   surface (pools/<pool-id>.md), generated by generate-pool-pages.js.

   PLAIN LANE — this file must never require the browser-driving test
   framework, directly or transitively. generate-pool-pages.js's own
   top-level dependency on the audit helper module DOES mention that
   framework's package name (its lazy-resolution code + comments), so this
   file loads generate-pool-pages.js via a COMPUTED path variable rather than
   a literal quoted relative-path string directly inside a require call — the
   exact workaround test_test_registry.js's own header comment documents,
   applied here because run-tests.js's lane classifier only recurses into a
   LITERAL local-require string pattern found anywhere in the scanned file's
   own source TEXT (comments included — never write out that literal pattern
   for the audit helper module even in prose). generate-token-pages.js and
   translations.js are required normally (literal paths): neither mentions
   that framework nor depends on the audit helper module, so both stay
   lane-safe. This file's own text, and every comment in it, also deliberately
   never spells out that framework's name — see run-tests.js: a file is
   classified by its OWN text containing the string, quite apart from any
   require call at all. Verify after any edit:
   `node run-tests.js --list --lane=plain` must list this file;
   `--lane=browser` must not.

   Generation happens ONLY via a child process into an OS temp dir (never
   `pools/` in the repo, never this file's own process — mirrors
   test_markdown_twins.js's execFileSync pattern for the identical reason).
   Constructed trust-rail/rate-note fixtures call the exported
   renderPoolPageMarkdown() directly (in-process, via the computed-path
   require above) — pure function, no filesystem writes.

   Run: node test_pool_twins.js */
'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const REPO_ROOT = __dirname;

// --- Computed-path require of generate-pool-pages.js (see header) ----------
const GEN_POOL_PAGES_PATH = path.join(REPO_ROOT, 'generate-pool-pages.js');
const genPool = require(GEN_POOL_PAGES_PATH);

// --- Ordinary (lane-safe) requires ------------------------------------------
const {
  APY_SANITY_LIMIT, formatApy, poolTotalApy,
} = require('./generate-token-pages.js');
const { translations, createTranslationFunction } = require('./translations.js');
const t = createTranslationFunction('en');

let passed = 0;
let total = 0;
function test(name, fn) {
  total++;
  try { fn(); passed++; console.log('  ✓ ' + name); }
  catch (err) { console.error('  ✗ ' + name + '\n    ' + err.message); process.exitCode = 1; }
}

// ---------------------------------------------------------------------------
// Generate the REAL 427-twin population once, via child process, into a
// scratch temp dir — never the repo's tracked pools/. Absolute --snapshot /
// --pages paths so it works regardless of the child's cwd (the scratch dir
// itself, matching test_markdown_twins.js's "never cwd === repo root" rule).
// ---------------------------------------------------------------------------
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'dg-213-pool-twins-'));
const SNAPSHOT_ABS = path.join(REPO_ROOT, 'data', 'pools-snapshot.json');
const TOKENS_ABS = path.join(REPO_ROOT, 'tokens');
const CHAINS_ABS = path.join(REPO_ROOT, 'chains');

assert.notStrictEqual(path.resolve(scratch), REPO_ROOT, 'refusing to run generator with cwd === repo root');
execFileSync('node', [
  GEN_POOL_PAGES_PATH, '--out', 'pools', '--snapshot', SNAPSHOT_ABS, '--pages', `${TOKENS_ABS},${CHAINS_ABS}`,
], { cwd: scratch, stdio: 'pipe' });

const twinsDir = path.join(scratch, 'pools');
const twinIds = fs.readdirSync(twinsDir).filter(f => f.endsWith('.md')).map(f => f.replace(/\.md$/, ''));

function readTwin(id) { return fs.readFileSync(path.join(twinsDir, id + '.md'), 'utf8'); }

// --- Real snapshot pools, by id (plain JSON parse — no need to go through
// generate-pool-pages.js's own loaders for this). --------------------------
const SNAPSHOT = JSON.parse(fs.readFileSync(SNAPSHOT_ABS, 'utf8'));
const snapshotById = new Map();
SNAPSHOT.pools.forEach(p => { if (p && p.pool) snapshotById.set(p.pool, p); });

console.log(`scratch run: ${twinIds.length} real twins written to ${twinsDir}`);

try {

// ===========================================================================
// 1. Per-pool identity — >=10 distinct real ids, each naming ITS OWN symbol/
//    project/chain/APY/TVL and never another pool's id. Plus >=1 sub-$10M
//    pool: NONE of the 734 committed snapshot pools clear that bar (verified:
//    every one is >= $10M), so per the operator's own directive that leg is
//    built from a constructed fixture record passed through the REAL
//    generator function directly, not silently dropped.
// ===========================================================================
console.log('\ncriterion 1 — per-pool identity, >=10 distinct real ids + 1 constructed sub-$10M pool');

const IDENTITY_SAMPLE_SIZE = 10;
const sampleIds = twinIds.slice().sort().slice(0, IDENTITY_SAMPLE_SIZE);
test(`>=${IDENTITY_SAMPLE_SIZE} distinct real generated twin ids are available to sample`, () => {
  assert.ok(twinIds.length >= IDENTITY_SAMPLE_SIZE, `only ${twinIds.length} real twins were generated`);
  assert.strictEqual(new Set(sampleIds).size, sampleIds.length, 'sample ids must be distinct');
});

// Constructed sub-$10M fixture (comment above explains why this cannot come
// from the real snapshot). Rendered via the REAL exported function, in-process.
const SUB_10M_FIXTURE = {
  pool: 'ffffffff-1111-2222-3333-444444444444',
  symbol: 'SUBFIX', project: 'aave-v3', chain: 'Optimism',
  tvlUsd: 50000, apyBase: 5.25, apyReward: 0.4, exposure: 'single', ilRisk: 'no',
};
test('sanity: the constructed sub-$10M fixture is actually sub-$10M (documents why it is constructed, not sampled)', () => {
  assert.ok(SUB_10M_FIXTURE.tvlUsd < 100000, 'fixture must be under the $100K floor to exercise this leg');
  const noneUnder100k = SNAPSHOT.pools.every(p => (p.tvlUsd || 0) >= 100000);
  assert.ok(noneUnder100k, 'sanity assumption: every real snapshot pool is >= $100K');
});
const subFixtureMd = genPool.renderPoolPageMarkdown(SUB_10M_FIXTURE, 'August 3, 2026', {});

// Identity fixtures: [id, poolRecord, mdText]
const identityFixtures = sampleIds.map(id => [id, snapshotById.get(id), readTwin(id)]);
identityFixtures.push([SUB_10M_FIXTURE.pool, SUB_10M_FIXTURE, subFixtureMd]);

identityFixtures.forEach(([id, pool, md]) => {
  test(`twin ${id} names its OWN symbol, project and chain, and states its APY and TVL`, () => {
    assert.ok(pool, `sanity: no pool record for ${id}`);
    assert.ok(md.startsWith(`# ${pool.symbol}`), `twin for ${id} must open naming its own symbol`);
    assert.ok(md.includes(pool.project), `twin for ${id} must name its own project (${pool.project})`);
    assert.ok(md.includes(pool.chain), `twin for ${id} must name its own chain (${pool.chain})`);
    assert.ok(md.includes(`**${t('totalApy')}:**`), `twin for ${id} must state its APY`);
    assert.ok(md.includes(`**${t('tvl')}:**`), `twin for ${id} must state its TVL`);
  });
});

test('cross-contamination: no twin in the identity sample contains any OTHER sampled pool\'s id', () => {
  const offenders = [];
  identityFixtures.forEach(([id, , md]) => {
    identityFixtures.forEach(([otherId]) => {
      if (otherId === id) return;
      if (md.includes(otherId)) offenders.push(`${id}.md contains foreign id ${otherId}`);
    });
  });
  assert.deepStrictEqual(offenders, [], offenders.join('; '));
});

// ===========================================================================
// 2. Trust rails in the new format — mutation-resistant: each assertion
//    directly checks a behavior that a removed rail would visibly break.
// ===========================================================================
console.log('\ncriterion 2 — trust rails (anomaly flag, sanity-limit sweep, degen haircut)');

const ANOMALOUS_FIXTURE = {
  pool: 'aaaaaaaa-0000-0000-0000-000000000001',
  symbol: 'ANOM', project: 'anomproj', chain: 'Ethereum',
  tvlUsd: 5000000, apyBase: APY_SANITY_LIMIT + 500, apyReward: 0,
};
const anomMd = genPool.renderPoolPageMarkdown(ANOMALOUS_FIXTURE, 'August 3, 2026', {});

test('constructed anomalous pool (APY > APY_SANITY_LIMIT): the ⚠ anomaly line is present', () => {
  assert.ok(poolTotalApy(ANOMALOUS_FIXTURE) > APY_SANITY_LIMIT, 'sanity: fixture must actually exceed the rail');
  assert.ok(anomMd.includes(t('calcAnomalyWarning')), 'expected the anomaly warning line, verbatim from translations.js');
});
test('constructed anomalous pool: risk level is High', () => {
  assert.ok(anomMd.includes(`## ${t('riskAssessment')}: ${t('highRisk')}`), 'expected a forced High risk heading');
});
test('constructed anomalous pool: ZERO projection/concrete-CTA numbers anywhere in the twin', () => {
  assert.ok(!anomMd.includes(t('projectionHeading')), 'must NOT contain the projection heading');
  assert.ok(!anomMd.includes('~$'), 'must NOT contain any concrete projected dollar figure (~$... pattern)');
  assert.ok(anomMd.includes(`[${t('gardenThisPoolCta')}]`), 'garden CTA must fall back to the non-concrete label, not a projected number');
});

test('sweep: no twin among all real generated twins states an APY above APY_SANITY_LIMIT without the anomaly flag present in that same file', () => {
  const offenders = [];
  twinIds.forEach(id => {
    const md = readTwin(id);
    const m = md.match(/\*\*.*?:\*\* ([\d,]+\.\d{2})% \(/); // "**Total APY:** X.XX% ("
    if (!m) { offenders.push(`${id}: could not parse a Total APY line at all`); return; }
    const apy = Number(m[1].replace(/,/g, ''));
    if (apy > APY_SANITY_LIMIT && !md.includes(t('calcAnomalyWarning'))) {
      offenders.push(`${id}: states ${apy}% (> ${APY_SANITY_LIMIT}%) with NO anomaly flag`);
    }
  });
  assert.deepStrictEqual(offenders, [], offenders.join('; '));
});

const DEGEN_FIXTURE = {
  // low liquidity (+40) + very-high-yield (+30) + newer-protocol 'pendle' (+15)
  // = 85 > 50 -> High risk / 'degen' garden persona / haircut applies. Total
  // APY (60%) stays well under APY_SANITY_LIMIT, so this is NOT the anomalous
  // case above — it exercises the SEPARATE degen-haircut rail.
  pool: 'bbbbbbbb-0000-0000-0000-000000000002',
  symbol: 'DEGEN', project: 'pendle', chain: 'Arbitrum',
  tvlUsd: 500000, apyBase: 60, apyReward: 0,
};
const degenMd = genPool.renderPoolPageMarkdown(DEGEN_FIXTURE, 'August 3, 2026', {});
const degenTotalApy = poolTotalApy(DEGEN_FIXTURE);
const haircutApy = degenTotalApy / 3;
const haircutAmount = genPool.DEFAULT_INVESTMENT * Math.pow(1 + haircutApy / 100, genPool.PROJECTION_YEARS);
const unHaircutAmount = genPool.DEFAULT_INVESTMENT * Math.pow(1 + degenTotalApy / 100, genPool.PROJECTION_YEARS);
const haircutAmountStr = Number(haircutAmount).toLocaleString('en-US', { maximumFractionDigits: 0 });
const unHaircutAmountStr = Number(unHaircutAmount).toLocaleString('en-US', { maximumFractionDigits: 0 });

test('sanity: the constructed degen fixture is NOT anomalous and DOES land in the degen tier', () => {
  assert.ok(degenTotalApy <= APY_SANITY_LIMIT, 'fixture must stay under the sanity rail (this is the haircut rail, not the anomaly rail)');
  assert.notStrictEqual(haircutAmountStr, unHaircutAmountStr, 'sanity: haircut and un-haircut amounts must differ for this fixture to be meaningful');
});
test('constructed degen-tier pool: the projection equals the ⅓-haircut value, computed from the rate (not a hardcoded literal)', () => {
  assert.ok(degenMd.includes(`~$${haircutAmountStr}`), `expected the haircut projection amount ~$${haircutAmountStr} in the twin`);
});
test('constructed degen-tier pool: the projection is NOT the un-haircut value (proves the rail is APPLIED, not just mentioned)', () => {
  assert.ok(!degenMd.includes(`~$${unHaircutAmountStr}`), `must not also/instead show the un-haircut ~$${unHaircutAmountStr}`);
});
test('constructed degen-tier pool: the haircut disclosure string is present, read from translations.js', () => {
  const expectedDisclosure = translations.en.poolDegenHaircutNote(formatApy(degenTotalApy));
  assert.ok(degenMd.includes(expectedDisclosure), `expected the disclosure "${expectedDisclosure}"`);
});

// ===========================================================================
// 3. Rate note — the REAL three-tier mutually-exclusive chain (rate-
//    volatility honesty note, then the track-record family, then the
//    no-history line), verified BOTH via constructed single-tier fixtures
//    (with an explicit "exactly one candidate fired" check) AND a sweep
//    across all 427 real generated twins for mutual exclusivity. Candidate
//    strings are computed from translations.js's own templates with each
//    pool's REAL numbers — never a re-typed literal — so this is a black-box
//    presence check, not a re-derivation of generate-pool-pages.js's gating
//    logic (a real fidelity regression here shows up as "0 or 2+ candidates
//    present", not as a hand-copied threshold silently agreeing with itself).
// ===========================================================================
console.log('\ncriterion 3 — rate note: three mutually-exclusive tiers, read from translations.js');

// candidatesFor(pool) -> [{ key, str }] for every tier STRUCTURALLY computable
// from this pool's own fields (regardless of whether it is the one that
// actually fires) — never encodes the ratio>=1.5 / stdev-ratio<=0.2
// thresholds themselves, only which inputs exist to plug into each template.
function candidatesFor(pool) {
  const cur = (pool.apyBase || 0) + (pool.apyReward || 0);
  const out = [];
  const mean30dPresent = typeof pool.apyMean30d === 'number' && Number.isFinite(pool.apyMean30d) &&
    pool.apyMean30d >= 0 && pool.apyMean30d <= APY_SANITY_LIMIT;
  if (mean30dPresent && cur > 0 && pool.apyMean30d > 0) {
    out.push({ key: 'volatility', str: t('rateVolatilityNote', formatApy(cur), formatApy(pool.apyMean30d)) });
  }
  if (pool.kpis && typeof pool.kpis === 'object') {
    out.push({ key: 'new', str: t('rateTrackRecordNew') });
    const hp = Number(pool.kpis.historyPoints);
    if (Number.isFinite(hp)) {
      if (typeof pool.kpis.apyStdev === 'number') out.push({ key: 'steady', str: t('rateTrackRecordSteady', hp) });
      out.push({ key: 'tracked', str: t('rateTrackRecordTracked', hp) });
    }
  }
  out.push({ key: 'unavailable', str: t('rateHistoryUnavailable') });
  return out;
}
function firedCandidates(md, pool) {
  return candidatesFor(pool).filter(c => md.includes(c.str));
}

const TIER_FIXTURES = {
  volatility: {
    pool: 'cccccccc-0000-0000-0000-000000000003', symbol: 'VOLF', project: 'someproj', chain: 'Base',
    tvlUsd: 12000000, apyBase: 10, apyReward: 0, apyMean30d: 3, // ratio 10/3 = 3.33 >= 1.5
  },
  new: {
    pool: 'cccccccc-0000-0000-0000-000000000004', symbol: 'NEWF', project: 'someproj', chain: 'Base',
    tvlUsd: 12000000, apyBase: 8, apyReward: 0, kpis: { historyPoints: 4 },
  },
  steady: {
    pool: 'cccccccc-0000-0000-0000-000000000005', symbol: 'STDF', project: 'someproj', chain: 'Base',
    tvlUsd: 12000000, apyBase: 10, apyReward: 0, kpis: { historyPoints: 14, apyStdev: 1 }, // 1/10 = 0.1 <= 0.2
  },
  tracked: {
    pool: 'cccccccc-0000-0000-0000-000000000006', symbol: 'TRKF', project: 'someproj', chain: 'Base',
    tvlUsd: 12000000, apyBase: 10, apyReward: 0, kpis: { historyPoints: 14, apyStdev: 5 }, // 5/10 = 0.5 > 0.2
  },
  unavailable: {
    pool: 'cccccccc-0000-0000-0000-000000000007', symbol: 'UNAF', project: 'someproj', chain: 'Base',
    tvlUsd: 12000000, apyBase: 8, apyReward: 0, // no kpis at all
  },
};
const EXPECTED_TRANSLATION_KEY = {
  volatility: 'rateVolatilityNote', new: 'rateTrackRecordNew', steady: 'rateTrackRecordSteady',
  tracked: 'rateTrackRecordTracked', unavailable: 'rateHistoryUnavailable',
};

Object.entries(TIER_FIXTURES).forEach(([tier, pool]) => {
  const md = genPool.renderPoolPageMarkdown(pool, 'August 3, 2026', {});
  test(`tier "${tier}": exactly one rate-note candidate fires, and it is the expected one`, () => {
    const fired = firedCandidates(md, pool);
    assert.strictEqual(fired.length, 1, `expected exactly 1 fired candidate for tier "${tier}", got ${fired.length}: ${fired.map(f => f.key).join(',')}`);
    assert.strictEqual(fired[0].key, tier, `expected tier "${tier}" to fire, got "${fired[0].key}"`);
  });
  test(`tier "${tier}": the fired string is read verbatim from translations.js's ${EXPECTED_TRANSLATION_KEY[tier]}`, () => {
    assert.ok(md.includes(t(EXPECTED_TRANSLATION_KEY[tier])) ||
      // parameterised templates: recompute with this pool's own real args
      candidatesFor(pool).some(c => c.key === tier && md.includes(c.str)),
      `expected the ${EXPECTED_TRANSLATION_KEY[tier]} template's output in the tier "${tier}" twin`);
  });
});

test('sweep: every one of the 427 real generated twins fires EXACTLY ONE rate-note candidate (mutual exclusivity holds at scale)', () => {
  const offenders = [];
  twinIds.forEach(id => {
    const pool = snapshotById.get(id);
    if (!pool) { offenders.push(`${id}: no matching snapshot record to compute candidates from`); return; }
    const md = readTwin(id);
    const fired = firedCandidates(md, pool);
    if (fired.length !== 1) offenders.push(`${id}: fired ${fired.length} candidate(s) (${fired.map(f => f.key).join(',') || 'none'})`);
  });
  assert.deepStrictEqual(offenders, [], offenders.slice(0, 10).join('; ') + (offenders.length > 10 ? ` ... +${offenders.length - 10} more` : ''));
});

// ===========================================================================
// 4. Both north-star CTAs, as labelled markdown links; garden CTA carries
//    src=pool.
// ===========================================================================
console.log('\ncriterion 4 — both north-star CTAs present as labelled markdown links');

test('a normal real twin has >=2 labelled markdown links, including a garden CTA carrying src=pool', () => {
  const id = sampleIds[0];
  const md = readTwin(id);
  const links = [...md.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)].map(m => m[1]);
  assert.ok(links.length >= 2, `expected >=2 markdown links in ${id}.md, got ${links.length}`);
  const gardenLinks = links.filter(u => u.includes('/plan.html') && u.includes('src=pool'));
  assert.ok(gardenLinks.length === 1, `expected exactly 1 garden CTA link carrying src=pool in ${id}.md, got ${gardenLinks.length}`);
});

// ===========================================================================
// 5. Twins are out of every sitemap.
// ===========================================================================
console.log('\ncriterion 5 — twins are out of every sitemap*.xml');

test('no sitemap*.xml file in the repo root mentions "/pools/"', () => {
  const files = fs.readdirSync(REPO_ROOT).filter(f => /^sitemap.*\.xml$/.test(f));
  assert.ok(files.length > 0, 'sanity: expected at least one sitemap*.xml in the repo root');
  const offenders = [];
  files.forEach(f => {
    const xml = fs.readFileSync(path.join(REPO_ROOT, f), 'utf8');
    if (xml.includes('/pools/')) offenders.push(f);
  });
  assert.deepStrictEqual(offenders, [], `these sitemaps reference /pools/: ${offenders.join(', ')}`);
});

// ===========================================================================
// 6. Zero new translation keys — every t('...') key generate-pool-pages.js
//    uses exists in BOTH translations.en and translations.ko. Parsed from
//    generate-pool-pages.js's own SOURCE TEXT (fs.readFileSync, never a
//    require of it a second time) so this stays independent of the
//    computed-path module object above.
// ===========================================================================
console.log('\ncriterion 6 — zero new translation keys (EN + KO parity)');

test('every t(\'key\') the generator uses exists in BOTH translations.en and translations.ko', () => {
  const src = fs.readFileSync(GEN_POOL_PAGES_PATH, 'utf8');
  const re = /(?:^|[^A-Za-z0-9_.])t\(\s*'([a-zA-Z0-9_]+)'/g;
  const keys = new Set();
  let m;
  while ((m = re.exec(src))) keys.add(m[1]);
  assert.ok(keys.size > 0, 'sanity: expected to find at least one t(\'...\') call in generate-pool-pages.js');
  const missingEn = [...keys].filter(k => !(k in translations.en));
  const missingKo = [...keys].filter(k => !(k in translations.ko));
  assert.deepStrictEqual(missingEn, [], `keys missing from translations.en: ${missingEn.join(', ')}`);
  assert.deepStrictEqual(missingKo, [], `keys missing from translations.ko: ${missingKo.join(', ')}`);
});

// ===========================================================================
// 7. Spec 216 — the `<id>.json` paint artifact sibling, proven against the
//    SAME real generator run (the scratch `pools/` dir populated above), not
//    a hand-written fixture. `projectPool` is required NORMALLY here (a
//    literal relative-path string): generate-pools-snapshot.js has no
//    transitive dependency on the browser-driving test framework or the
//    audit helper module (unlike generate-pool-pages.js itself — see this
//    file's header), so importing it directly does not move this file out of
//    the plain lane.
// ===========================================================================
console.log('\ncriterion 7 — spec 216: <id>.json paint artifact sibling, reuse-by-import proven');

const { projectPool: realProjectPool } = require('./generate-pools-snapshot.js');

function readTwinJson(id) { return JSON.parse(fs.readFileSync(path.join(twinsDir, id + '.json'), 'utf8')); }
const jsonIds = fs.readdirSync(twinsDir).filter(f => f.endsWith('.json')).map(f => f.replace(/\.json$/, ''));

test('one .json sibling per .md twin, and vice versa — identical id sets', () => {
  assert.deepStrictEqual([...jsonIds].sort(), [...twinIds].sort(), 'the .json and .md id sets must match exactly');
});

test(`every one of the ${twinIds.length} real .json twins parses, schemaVersion===1, count===1, pools.length===1, minTvlUsd===1000, and its record is deep-equal to projectPool() of the same input pool (proves the shared projection is REUSED, not re-implemented)`, () => {
  const offenders = [];
  twinIds.forEach(id => {
    const sourcePool = snapshotById.get(id);
    if (!sourcePool) { offenders.push(`${id}: no matching snapshot record to compare against`); return; }
    let art;
    try { art = readTwinJson(id); } catch (e) { offenders.push(`${id}: .json did not parse (${e.message})`); return; }
    if (art.schemaVersion !== 1) offenders.push(`${id}: schemaVersion !== 1 (got ${art.schemaVersion})`);
    if (art.count !== 1) offenders.push(`${id}: count !== 1 (got ${art.count})`);
    if (!Array.isArray(art.pools) || art.pools.length !== 1) offenders.push(`${id}: pools.length !== 1`);
    if (art.minTvlUsd !== 1000) offenders.push(`${id}: minTvlUsd !== 1000 (got ${art.minTvlUsd}) — must state the artifact's OWN $1,000 floor, never the snapshot's $10M`);
    try {
      assert.deepStrictEqual(art.pools[0], realProjectPool(sourcePool));
    } catch (e) {
      offenders.push(`${id}: record is not deep-equal to projectPool(sourcePool)`);
    }
  });
  assert.deepStrictEqual(offenders, [], offenders.slice(0, 10).join('; ') + (offenders.length > 10 ? ` ... +${offenders.length - 10} more` : ''));
});

test('a .json artifact\'s generatedAt is a valid, recent ISO timestamp (never the human-readable Markdown date string)', () => {
  const id = twinIds[0];
  const art = readTwinJson(id);
  const parsed = new Date(art.generatedAt).getTime();
  assert.ok(Number.isFinite(parsed), `generatedAt "${art.generatedAt}" must parse as a valid date`);
  const ageMs = Date.now() - parsed;
  assert.ok(ageMs >= 0 && ageMs < 5 * 60 * 1000, `generatedAt must be a fresh timestamp from this very run, got age ${ageMs}ms`);
});

test('reuse proven by import, not by resemblance: generate-pool-pages.js obtains projectPool AND envelope via require(\'./generate-pools-snapshot.js\') — a copied body is a FAIL', () => {
  const src = fs.readFileSync(GEN_POOL_PAGES_PATH, 'utf8');
  assert.ok(
    /require\(\s*['"]\.\/generate-pools-snapshot\.js['"]\s*\)/.test(src),
    'expected a literal require(\'./generate-pools-snapshot.js\') in generate-pool-pages.js'
  );
  assert.ok(/\{\s*projectPool\s*,\s*envelope\s*\}/.test(src) || (src.includes('projectPool') && src.includes('envelope')),
    'expected generate-pool-pages.js to destructure projectPool and envelope from the required module');
});

console.log('stale-cleanup — a junk .json left in the out dir is removed on the next real generator run');
test('re-running the REAL generator removes an orphaned .json artifact, and real twins survive the re-run', () => {
  const junkPath = path.join(twinsDir, 'zzzzzzzz-0000-0000-0000-000000000000.json');
  fs.writeFileSync(junkPath, JSON.stringify({ schemaVersion: 1, generatedAt: '2020-01-01T00:00:00.000Z', source: 'stale', minTvlUsd: 1000, count: 1, pools: [{ pool: 'stale' }] }));
  assert.ok(fs.existsSync(junkPath), 'sanity: junk .json was written');
  execFileSync('node', [
    GEN_POOL_PAGES_PATH, '--out', 'pools', '--snapshot', SNAPSHOT_ABS, '--pages', `${TOKENS_ABS},${CHAINS_ABS}`,
  ], { cwd: scratch, stdio: 'pipe' });
  assert.ok(!fs.existsSync(junkPath), 'stale .json must be removed by the next generator run');
  assert.ok(fs.existsSync(path.join(twinsDir, twinIds[0] + '.json')), 'a real twin\'s .json must survive the re-run');
  assert.ok(fs.existsSync(path.join(twinsDir, twinIds[0] + '.md')), 'a real twin\'s .md must survive the re-run');
});

} finally {
  fs.rmSync(scratch, { recursive: true, force: true });
}

console.log(`\n${passed}/${total} pool-twin assertions passed`);
if (passed !== total) console.error('\n❌ some assertions failed');
