#!/usr/bin/env python3
"""
b2b_treasury_voucher_engine.py - B2B Treasury Voucher & Outbound Automation Engine

Generates personalized DeFi Garden v2 Intent-Resolved Treasury Voucher URLs,
calculates rigorous mathematical financial proofs, and outputs formatted,
multi-channel cold outreach copy for Web3 Founders, CFOs, and DAO Ops leads.

Part of Stage 2 GTM Execution for DeFi Garden v2.
"""

import sys
import os
import json
import argparse
import urllib.parse
from typing import Dict, List, Any, Optional

# Core Canonical Mathematical Constants (mirrored from trust-rails.js & PRD-002)
CONSERVATIVE_NET_APY = 0.0510      # 5.10% conservative Base net APY (Aave V3 / Morpho Blue)
TAX_HEADROOM_MULTIPLIER = 1.20    # +20% buffer for US state sales tax / EU VAT slippage
SAFETY_BUFFER_MULTIPLIER = 1.25   # 1.25x over-collateralization against floating APY decay
DEFAULT_BASE_URL = "https://www.defi.garden/plan.html"


def calculate_financial_proof(monthly_saas_usd: float, custom_apy: Optional[float] = None) -> Dict[str, Any]:
    """
    Computes mathematical financial proofs for a given monthly SaaS liability.
    """
    net_apy = custom_apy if custom_apy is not None else CONSERVATIVE_NET_APY
    
    # Step 1: Base annual liability
    annual_raw_liability = monthly_saas_usd * 12.0
    
    # Step 2: Tax-buffered liability
    monthly_effective_liability = monthly_saas_usd * TAX_HEADROOM_MULTIPLIER
    annual_tax_adjusted_liability = annual_raw_liability * TAX_HEADROOM_MULTIPLIER
    
    # Step 3: Unbuffered theoretical capital requirement
    unbuffered_capital = annual_tax_adjusted_liability / net_apy
    
    # Step 4: Hardened Treasury Allocation (with 1.25x Safety Buffer)
    required_treasury_deposit = round(unbuffered_capital * SAFETY_BUFFER_MULTIPLIER)
    
    # Step 5: Monthly and Annual Gross Yield generated by the allocated deposit
    annual_gross_yield = required_treasury_deposit * net_apy
    monthly_gross_yield = annual_gross_yield / 12.0
    
    # Step 6: Surplus Sponge allocation (excess yield diverted to 3-month escrow reserve)
    monthly_surplus = monthly_gross_yield - monthly_effective_liability
    annual_surplus = monthly_surplus * 12.0
    
    # Step 7: 5-Year Cumulative P&L Cashflow Savings
    five_year_savings = annual_raw_liability * 5.0
    
    return {
        "monthly_saas_raw_usd": round(monthly_saas_usd, 2),
        "annual_saas_raw_usd": round(annual_raw_liability, 2),
        "tax_headroom_multiplier": TAX_HEADROOM_MULTIPLIER,
        "monthly_tax_adjusted_usd": round(monthly_effective_liability, 2),
        "annual_tax_adjusted_usd": round(annual_tax_adjusted_liability, 2),
        "conservative_net_apy_pct": round(net_apy * 100.0, 2),
        "safety_buffer_multiplier": SAFETY_BUFFER_MULTIPLIER,
        "required_treasury_deposit_usdc": required_treasury_deposit,
        "monthly_gross_yield_usd": round(monthly_gross_yield, 2),
        "annual_gross_yield_usd": round(annual_gross_yield, 2),
        "monthly_surplus_escrow_usd": round(monthly_surplus, 2),
        "annual_surplus_escrow_usd": round(annual_surplus, 2),
        "five_year_cumulative_savings_usd": round(five_year_savings, 2),
        "principal_retained_pct": 100.0,
        "bank_out_of_pocket_usd": 0.0
    }


def generate_voucher_url(
    company_name: str,
    monthly_saas_usd: float,
    saas_stack: str = "Slack + Notion + GitHub + AWS",
    ref_tag: str = "b2b_outbound_q3",
    custom_apy: Optional[float] = None
) -> str:
    """
    Constructs the dynamic, pre-solved DeFi Garden intent voucher URL.
    """
    proof = calculate_financial_proof(monthly_saas_usd, custom_apy)
    
    params = {
        "company": company_name,
        "bill": str(int(round(monthly_saas_usd))),
        "capital": str(proof["required_treasury_deposit_usdc"]),
        "preset": "treasury_shield",
        "stack": saas_stack,
        "chain": "base",
        "token": "USDC",
        "ref": ref_tag
    }
    
    return f"{DEFAULT_BASE_URL}?{urllib.parse.urlencode(params)}"


def generate_outreach_templates(
    lead_name: str,
    company_name: str,
    monthly_saas_usd: float,
    saas_stack: str = "Slack + Notion + GitHub + AWS",
    sender_name: str = "Alex",
    custom_apy: Optional[float] = None
) -> Dict[str, Dict[str, str]]:
    """
    Generates high-converting, zero-fluff cold outreach copy for 3 personas across 4 channels.
    """
    proof = calculate_financial_proof(monthly_saas_usd, custom_apy)
    voucher_url = generate_voucher_url(company_name, monthly_saas_usd, saas_stack)
    
    bill_str = f"${int(round(monthly_saas_usd)):,}"
    annual_str = f"${int(round(proof['annual_saas_raw_usd'])):,}"
    deposit_str = f"${int(proof['required_treasury_deposit_usdc']):,}"
    five_year_str = f"${int(round(proof['five_year_cumulative_savings_usd'])):,}"
    
    return {
        "founder": {
            "warpcast": (
                f"Hey @{lead_name} — saw {company_name}'s recent momentum on Base. "
                f"Your team is likely burning ~{bill_str}/mo on {saas_stack}. "
                f"We built an onchain treasury vault that wipes that {annual_str}/yr SaaS burn off your P&L forever by parking {deposit_str} USDC in an audited non-custodial Base vault while you keep 100% principal.\n\n"
                f"Pre-calculated your custom voucher & proof here: {voucher_url}\n\n"
                f"Want a 5-min sandbox walkthrough to test card issuance?"
            ),
            "telegram": (
                f"Hey {lead_name}, quick note on {company_name}'s runway efficiency.\n\n"
                f"If your team burns ~{bill_str}/mo on {saas_stack}, you're leaking {annual_str}/year straight out of your bank account. "
                f"With DeFi Garden, you allocate {deposit_str} USDC from your idle Base treasury into an audited ERC-4626 vault (Aave/Morpho). "
                f"The accrued yield auto-pays your SaaS bills via a virtual corporate Visa card. Your principal remains 100% self-custodial in your Multisig Safe.\n\n"
                f"Here is your pre-calculated team voucher: {voucher_url}\n\n"
                f"Open to a 5-minute preview this week?"
            ),
            "email_subject": f"Zero-burn SaaS for {company_name} ({annual_str}/yr P&L recovery)",
            "email_body": (
                f"Hi {lead_name},\n\n"
                f"Quick math on {company_name}'s operational runway:\n\n"
                f"At an estimated team size and tech stack ({saas_stack}), you are spending ~{bill_str}/month ({annual_str}/year) in pure cash burn.\n\n"
                f"Instead of draining fiat reserves, you can allocate {deposit_str} USDC of idle treasury on Base into a DeFi Garden non-custodial vault.\n\n"
                f"• Yield covers 100% of recurring team software bills.\n"
                f"• 1.25x safety buffer + 20% tax buffer prevents card declines.\n"
                f"• 100% of principal remains in your team's control (instant withdrawal at any time).\n"
                f"• 5-year cumulative cash savings: {five_year_str}.\n\n"
                f"I generated a customized voucher and yield breakdown for {company_name}:\n"
                f"{voucher_url}\n\n"
                f"Do you have 10 minutes on Thursday to review the non-custodial vault architecture?\n\n"
                f"Best,\n{sender_name}"
            ),
            "linkedin": (
                f"Hi {lead_name} — noticed {company_name}'s growth. Web3 teams of your scale typically burn ~{bill_str}/mo on tools like {saas_stack}. "
                f"We built a non-custodial treasury vault on Base that converts idle stablecoins into automated corporate Visa payments, eliminating {annual_str}/yr in SaaS P&L while keeping 100% principal intact. "
                f"Pre-modeled your numbers here: {voucher_url} — open to reviewing the smart contract security rails?"
            )
        },
        "cfo": {
            "warpcast": (
                f"@{lead_name} — regarding {company_name}'s balance sheet efficiency: "
                f"parking {deposit_str} USDC into our audited ERC-4626 Base vault completely offsets your ~{bill_str}/mo ({annual_str}/yr) SaaS liabilities via automated virtual Visa settlement. "
                f"Zero counterparty custody (Multisig Safe compatible), 1.25x over-collateralization buffer, and 1-click CSV accounting exports.\n\n"
                f"Financial model & voucher: {voucher_url}\n"
                f"Can I share our audit report & security spec?"
            ),
            "telegram": (
                f"Hi {lead_name}, reaching out regarding {company_name}'s treasury management.\n\n"
                f"We built DeFi Garden for Web3 finance leads who want zero-risk P&L optimization. By allocating {deposit_str} USDC into an audited ERC-4626 vault on Base (routing to Aave V3 & Morpho Blue), you generate enough recurring yield to extinguish ~{bill_str}/mo in software liabilities ({saas_stack}).\n\n"
                f"Key CFO safeguards:\n"
                f"1. Self-custodial: Governed entirely by your Safe Multisig; unconditional instant withdrawal.\n"
                f"2. Volatility buffer: 1.25x capital buffer + 1-month liquid yield escrow against APY compression.\n"
                f"3. Reconciliation: Automated 1st-of-the-month settlement receipts + Quickbooks/Xero CSV tagging.\n\n"
                f"Here is your interactive financial proof: {voucher_url}\n\n"
                f"Do you have 10 minutes this week to walk through the risk parameters?"
            ),
            "email_subject": f"{company_name} Treasury: Eliminating {annual_str}/yr SaaS liability via Base ERC-4626",
            "email_body": (
                f"Hi {lead_name},\n\n"
                f"I'm reaching out to share a treasury optimization model built specifically for Web3 finance leads.\n\n"
                f"Based on {company_name}'s profile, your team carries roughly {bill_str}/month ({annual_str}/year) in SaaS overhead ({saas_stack}).\n\n"
                f"DeFi Garden's Treasury Shield allows you to eliminate this line-item expense from your P&L entirely:\n\n"
                f"• Capital Allocation: {deposit_str} USDC on Base.\n"
                f"• Yield Source: Audited Aave V3 & Morpho Blue vaults (~{proof['conservative_net_apy_pct']}% net conservative APY).\n"
                f"• Safety Rails: 1.25x over-collateralization + 20% tax headroom + 3-month Surplus Sponge.\n"
                f"• Custody: 100% non-custodial (Safe Multisig 4337 compatible); zero lockups or withdrawal penalties.\n"
                f"• Payment Rails: Rain BaaS Commercial Visa BIN with Apple Pay & monthly settlement webhooks.\n\n"
                f"You can inspect the customized financial proof and voucher for {company_name} here:\n"
                f"{voucher_url}\n\n"
                f"Are you open to a brief 10-minute technical review of our smart contract architecture and audit reports?\n\n"
                f"Best regards,\n{sender_name}"
            ),
            "linkedin": (
                f"Hi {lead_name} — quick note for your finance desk at {company_name}. We developed an audited ERC-4626 vault on Base that offsets {annual_str}/yr in team software overhead by routing {deposit_str} USDC of idle treasury into automated Visa card settlement. 100% self-custodial with instant liquidity. "
                f"Review your customized financial model here: {voucher_url} — open to a quick technical brief?"
            )
        },
        "dao_ops": {
            "warpcast": (
                f"Hey @{lead_name} — quick operational note for {company_name}. "
                f"DAOs often struggle with paying recurring Web2 infrastructure ({saas_stack}) without manual monthly reimbursements. "
                f"With DeFi Garden, the DAO deposits {deposit_str} USDC from the Safe once. Accrued Base yield perpetually settles the team's ~{bill_str}/mo bills onchain via virtual Visa cards. Principal stays 100% locked in DAO control.\n\n"
                f"Voucher & proposal preview: {voucher_url}\n"
                f"Want a pre-drafted governance proposal template?"
            ),
            "telegram": (
                f"Hey {lead_name}, reaching out to {company_name} operations.\n\n"
                f"Managing monthly SaaS reimbursements ({saas_stack} @ ~{bill_str}/mo) is a recurring administrative pain for DAO operations. "
                f"We created a plug-and-play Safe Module / ERC-4626 vault on Base: the DAO parks {deposit_str} USDC in self-custodial yield vaults, and the realized yield automatically funds a dedicated corporate Visa card for core contributors.\n\n"
                f"• Zero manual contributor reimbursements.\n"
                f"• 100% onchain auditability.\n"
                f"• 0% principal risk — withdrawable anytime by Safe signers.\n\n"
                f"Check out {company_name}'s live voucher setup: {voucher_url}\n\n"
                f"Would this be helpful for your operations workstream?"
            ),
            "email_subject": f"Automating {company_name}'s Web2 infrastructure spend ({bill_str}/mo) via Safe yield",
            "email_body": (
                f"Hi {lead_name},\n\n"
                f"Managing team SaaS subscriptions ({saas_stack}) in a DAO environment usually means messy credit card sharing or manual monthly contributor expense reports.\n\n"
                f"DeFi Garden provides a dedicated onchain treasury solution for {company_name}:\n\n"
                f"1. One-Time Setup: Allocate {deposit_str} USDC from your DAO Safe into our audited Base ERC-4626 vault.\n"
                f"2. Automated Payment: Realized yield auto-funds a virtual commercial Visa card capped at {bill_str}/month.\n"
                f"3. Governance & Control: Principal never leaves your Safe's ultimate authority; zero lockups.\n"
                f"4. Net Financial Impact: Eliminates {annual_str}/yr in operational expenses forever.\n\n"
                f"I've configured a custom proposal voucher for {company_name}:\n"
                f"{voucher_url}\n\n"
                f"Could I send over our 1-page DAO Governance Proposal template for your ops workstream to review?\n\n"
                f"Best,\n{sender_name}"
            ),
            "linkedin": (
                f"Hi {lead_name} — managing recurring team SaaS at {company_name} ({bill_str}/mo) without messy reimbursements is now solvable onchain. DeFi Garden lets your DAO allocate {deposit_str} USDC into an audited Base vault to auto-pay {saas_stack} via virtual Visa cards while retaining 100% self-custody. "
                f"Custom preview: {voucher_url} — open to reviewing the Safe integration?"
            )
        }
    }


def qualify_account(
    company_name: str,
    treasury_stablecoins_usd: float,
    team_size: int,
    estimated_monthly_burn: float,
    multisig_type: str = "Safe",
    primary_chain: str = "Base"
) -> Dict[str, Any]:
    """
    Scores an inbound or outbound lead against the Stage 2 TREASURY-FIT Framework.
    """
    score = 0
    reasons = []
    disqualified = False
    disqualify_reason = None
    
    # Gate 1: Liquidity Check
    if treasury_stablecoins_usd < 100000:
        disqualified = True
        disqualify_reason = f"Treasury stablecoins (${treasury_stablecoins_usd:,.0f}) below $100K minimum threshold."
    elif treasury_stablecoins_usd >= 1000000:
        score += 40
        reasons.append("High Liquidity (>=$1M stablecoins): +40 pts")
    elif treasury_stablecoins_usd >= 300000:
        score += 30
        reasons.append("Solid Liquidity ($300k-$1M stablecoins): +30 pts")
    else:
        score += 20
        reasons.append("Sufficient Liquidity ($100k-$300k stablecoins): +20 pts")
        
    # Gate 2: Team Size & SaaS Burn
    if team_size >= 10:
        score += 25
        reasons.append(f"Optimal Team Size ({team_size} members, ${estimated_monthly_burn:,.0f}/mo burn): +25 pts")
    elif team_size >= 4:
        score += 20
        reasons.append(f"Viable Team Size ({team_size} members, ${estimated_monthly_burn:,.0f}/mo burn): +20 pts")
    else:
        score += 10
        reasons.append(f"Small Pod ({team_size} members): +10 pts")
        
    # Gate 3: Multisig / Safe Infrastructure
    if "safe" in multisig_type.lower() or "gnosis" in multisig_type.lower():
        score += 20
        reasons.append("Safe Multisig Native: +20 pts")
    else:
        score += 10
        reasons.append(f"Alternative Wallet Setup ({multisig_type}): +10 pts")
        
    # Gate 4: Chain Ecosystem Alignment
    if primary_chain.lower() in ["base", "optimism", "arbitrum", "ethereum"]:
        score += 15
        reasons.append(f"EVM/L2 Native ({primary_chain}): +15 pts")
    else:
        score += 5
        reasons.append(f"Non-EVM / Alt L1 ({primary_chain}): +5 pts")
        
    # Determine Tier
    if disqualified:
        tier = "DISQUALIFIED"
        action = "Archive / Nurture on low-priority newsletter."
    elif score >= 80:
        tier = "TIER_1_IMMEDIATE_PILOT"
        action = "Direct multi-channel outbound sprint (CEO + CFO + Ops). Target close within 7 days."
    elif score >= 60:
        tier = "TIER_2_FAST_TRACK"
        action = "Standard outbound sequence (Touch 1-4). Target close within 14 days."
    else:
        tier = "TIER_3_INCUBATION"
        action = "Add to self-serve waitlist and community education loop."
        
    return {
        "company": company_name,
        "score": score if not disqualified else 0,
        "tier": tier,
        "disqualified": disqualified,
        "disqualify_reason": disqualify_reason,
        "recommended_action": action,
        "score_breakdown": reasons
    }


def main():
    parser = argparse.ArgumentParser(description="DeFi Garden v2 B2B Treasury Voucher & Outbound Engine")
    parser.add_argument("--company", type=str, default="NexusProtocol", help="Target company name")
    parser.add_argument("--bill", type=float, default=400.0, help="Monthly SaaS liability in USD")
    parser.add_argument("--stack", type=str, default="Slack + Notion + GitHub + AWS", help="SaaS software stack description")
    parser.add_argument("--persona", type=str, choices=["founder", "cfo", "dao_ops", "all"], default="all", help="Target persona")
    parser.add_argument("--channel", type=str, choices=["warpcast", "telegram", "email", "linkedin", "all"], default="all", help="Communication channel")
    parser.add_argument("--treasury", type=float, default=500000.0, help="Estimated treasury stablecoin balance")
    parser.add_argument("--team-size", type=int, default=8, help="Team member count")
    parser.add_argument("--json-output", action="store_true", help="Output results in JSON format")

    args = parser.parse_args()

    proof = calculate_financial_proof(args.bill)
    voucher_url = generate_voucher_url(args.company, args.bill, args.stack)
    outreach = generate_outreach_templates(
        lead_name=args.company + "_Lead",
        company_name=args.company,
        monthly_saas_usd=args.bill,
        saas_stack=args.stack
    )
    qualification = qualify_account(
        company_name=args.company,
        treasury_stablecoins_usd=args.treasury,
        team_size=args.team_size,
        estimated_monthly_burn=args.bill
    )

    if args.json_output:
        result = {
            "company": args.company,
            "voucher_url": voucher_url,
            "financial_proof": proof,
            "qualification": qualification,
            "outreach_templates": outreach
        }
        print(json.dumps(result, indent=2))
        return

    print("=" * 80)
    print(f"🌱 DEFI GARDEN v2 — B2B TREASURY VOUCHER ENGINE")
    print("=" * 80)
    print(f"Company Target:       {args.company}")
    print(f"Monthly SaaS Burn:    ${args.bill:,.2f}/mo  (Annual: ${proof['annual_saas_raw_usd']:,.2f}/yr)")
    print(f"Software Stack:       {args.stack}")
    print(f"Required Treasury:    ${proof['required_treasury_deposit_usdc']:,} USDC (@ {proof['conservative_net_apy_pct']}% net APY)")
    print(f"5-Year Savings:       ${proof['five_year_cumulative_savings_usd']:,.2f} cashflow retained")
    print(f"Voucher Deep Link:    {voucher_url}")
    print("-" * 80)
    print(f"🎯 ACCOUNT QUALIFICATION: {qualification['tier']} (Score: {qualification['score']}/100)")
    print(f"Action: {qualification['recommended_action']}")
    for r in qualification["score_breakdown"]:
        print(f"  • {r}")
    print("=" * 80)
    print("📋 OUTREACH TEMPLATES PREVIEW (FOUNDER - WARPCAST):")
    print(outreach["founder"]["warpcast"])
    print("-" * 80)
    print("📋 OUTREACH TEMPLATES PREVIEW (CFO - TELEGRAM):")
    print(outreach["cfo"]["telegram"])
    print("-" * 80)
    print("📋 OUTREACH TEMPLATES PREVIEW (DAO OPS - EMAIL SUBJECT & BODY):")
    print(f"Subject: {outreach['dao_ops']['email_subject']}")
    print(outreach['dao_ops']['email_body'])
    print("=" * 80)


if __name__ == "__main__":
    main()
